# Generated by Django 5.0.7 on 2024-07-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
