# Generated by Django 5.0.7 on 2024-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse')], max_length=100),
        ),
    ]
