# Generated by Django 5.0.7 on 2024-07-25 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_asset_quantity_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Desktop', 'Desktop'), ('Chairs', 'Chairs'), ('Tables', 'Tables'), ('Sound-System', 'Sound-System')], max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Refubrished', 'Refubrished'), ('Second-hand', 'Second-hand')], max_length=50),
        ),
    ]
