# Generated by Django 5.0.7 on 2024-07-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_asset_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
    ]
