# Generated by Django 5.0.7 on 2024-07-27 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('organisation_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_picked', models.DateField(default=django.utils.timezone.now)),
                ('date_to_return', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.asset')),
            ],
        ),
    ]
