# Generated by Django 5.0.7 on 2024-07-27 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_assetassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('organisation_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_picked', models.DateField()),
                ('date_to_return', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.asset')),
            ],
        ),
    ]
