# Generated by Django 5.0.7 on 2024-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_damagedasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagedasset',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='damagedasset',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='damagedasset',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='damagedasset',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='damagedasset',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
