# Generated by Django 5.0.7 on 2024-07-29 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_damagedasset_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedasset',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
