# Generated by Django 5.0.7 on 2024-07-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_damagedasset_date_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagedasset',
            name='fixed',
        ),
        migrations.AlterField(
            model_name='damagedasset',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='damagedasset',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
