# Generated by Django 5.0.7 on 2024-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_damagedasset_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
